### ISSUE TITLE
Accept multiple items

### ISSUE THREAD

**Issue by jacques-navarro** [Muir-Fionn/Slackbot-Using-Botkit#2]
Allow user to add multiple items per entry.

We can separate items with spaces or with commas.
for example: `add pizza bananas` or `add pizza, bananas`

**Comment by Muir-Fionn** [comment]
Considering some items are two words, probably best to only allow comma separation.
`add pizza, rolls, bananas` vs `add pizza rolls, bananas`

We'll also need to test how multiple words are brought over in the message.match object.

**Comment by Muir-Fionn** [comment]
Code updated to allow for multiple items to be added at once using comma separators.

**Comment by jacques-navarro** [comment]
Next time try adding `'closes #<issue number>'` and Github will close the issue automatically and insert the commit hash. It's handy to track down bugs that pop up after a change/commit.

[Closing issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by Muir-Fionn** [comment]
Had no clue you could even do that.  Thanks for letting me know.
